### ISSUE TITLE
Interfacing an Keithley current amplifier via a NI GPIB/ENET 1000

### ISSUE THREAD

**Issue by Haasens** [hgrecco/pyvisa-py#79]
Hi,

at first I have following setup of pyvisa:

    Machine Details:
       Platform ID:    Linux-3.12.53-40-desktop-x86_64-with-SuSE-13.1-x86_64
       Processor:      x86_64

    Python:
       Implementation: CPython
       Executable:     /usr/bin/python
       Version:        2.7.6
       Compiler:       GCC
       Bits:           64bit
       Build:          Nov 21 2013 15:55:38 (#default)
       Unicode:        UCS4

    PyVISA Version: 1.8

    Backends:
       ni:
           Version: 1.8 (bundled with PyVISA)
           Binary library: Not found
       py:
           Version: 0.2
           ASRL INSTR: Available via PySerial (3.0.1)
           TCPIP INSTR: Available 
           USB RAW: Available via PyUSB (1.0.0rc1). Backend: libusb1
           USB INSTR: Available via PyUSB (1.0.0rc1). Backend: libusb1
           GPIB INSTR: Available 
           TCPIP SOCKET: Available 

I'm trying to interface an Keithley current amplifier (gpib port 23) via a NI GPIB/ENET 1000.
As I understand from the manual I have to use to interface the ENET controller the "ASRL-String". The ENET controller is working with the IP 192.168.62.39 and Port 5000. Now I tried to connect to the Keithley via the enet with:

     import visa
     rm = visa.ResourceManager('@py')
     inst = rm.open_resource('ASRL23::192.168.62.39::5000::INSTR')

I got following error:

     Traceback (most recent call last):                                                                                  
       File "<stdin>", line 1, in <module>                                                                               
       File "/usr/lib64/python2.7/site-packages/pyvisa/highlevel.py", line 1626, in open_resource                        
       resource_pyclass = self._resource_classes[(info.interface_type, info.resource_class)]
     AttributeError: 'int' object has no attribute 'interface_type'

I'm completely new to gpib, pyvisa and pyvisa-py and I hope somebody can help. That would be great!
Thanks a lot!!!

**Comment by DavidLutton** [comment]
The NI GPIB/ENET 1000 you referred to is not currently supported,
You may have found [VISA resource names — PyVISA documentation](http://pyvisa.readthedocs.io/en/latest/names.html?highlight=ENET) has an ENET-Serial resource name which is a different model of NI ENET device
